# Force npm install instead of npm ci
[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]
cacheDirectories = []

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
